openapi: 3.0.2
info:
  title: 'News Portal API'
  version: '1.0'
paths:
  /newsapp/:
    get:
      operationId: listNews
      description: 'Retrieve a list of news articles'
      parameters:
        - name: limit
          in: query
          required: false
          description: 'The maximum number of results to return'
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: 'The offset from which to start returning results'
          schema:
            type: integer
      responses:
        '200':
          description: 'A list of news articles'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/News'
      tags:
        - news
    post:
      operationId: createNews
      description: 'Create a new news article'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/News'
      responses:
        '201':
          description: 'The created news article'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
      tags:
        - news
  /news/{id}:
    get:
      operationId: getNewsById
      description: 'Retrieve a news article by ID'
      parameters:
        - name: id
          in: path
          required: true
          description: 'The ID of the news article'
          schema:
            type: string
      responses:
        '200':
          description: 'A single news article'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        '404':
          description: 'News article not found'
      tags:
        - news
    put:
      operationId: updateNews
      description: 'Update a news article by ID'
      parameters:
        - name: id
          in: path
          required: true
          description: 'The ID of the news article'
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/News'
      responses:
        '200':
          description: 'News article updated successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        '404':
          description: 'News article not found'
      tags:
        - news
    delete:
      operationId: deleteNews
      description: 'Delete a news article by ID'
      parameters:
        - name: id
          in: path
          required: true
          description: 'The ID of the news article'
          schema:
            type: string
      responses:
        '204':
          description: 'News article deleted successfully'
        '404':
          description: 'News article not found'
      tags:
        - news
components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 128
        content:
          type: string
      required:
        - title
        - content
    Comment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        text:
          type: string
        news:
          type: integer
          description: 'The ID of the news article'
      required:
        - text
        - news