# Generated by Django 5.1.2 on 2024-12-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('AR', 'Новость'), ('NW', 'Статья')], default='AR', help_text='Тип поста', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_type_en',
            field=models.CharField(choices=[('AR', 'Новость'), ('NW', 'Статья')], default='AR', help_text='Тип поста', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_type_ru',
            field=models.CharField(choices=[('AR', 'Новость'), ('NW', 'Статья')], default='AR', help_text='Тип поста', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Headline'),
        ),
    ]
