# Generated by Django 5.1.2 on 2025-01-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_alter_post_category_type_alter_post_category_type_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.category'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.category'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='post_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.post'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='post_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', through='newsapp.PostCategory', to='newsapp.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('AR', 'Article'), ('NW', 'News')], default='AR', help_text='Post type', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_type_en',
            field=models.CharField(choices=[('AR', 'Article'), ('NW', 'News')], default='AR', help_text='Post type', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_type_ru',
            field=models.CharField(choices=[('AR', 'Article'), ('NW', 'News')], default='AR', help_text='Post type', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
